### ISSUE TITLE
user case on random images?

### ISSUE THREAD

**Issue by fatginger1024** [cnexah/VA-DepthNet#3]
Hi there! I was trying to get your wondnerful model tested on a random image when I encountered this bug, could you please help me out there?
Below is the code to reproduce the error:
<code>
import torch
from vadepthnet.networks.vadepthnet import VADepthNet
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device: %s" % device)
model = VADepthNet(max_depth=2,
                   prior_mean=.6,
                   img_size=(480, 640))
model = torch.nn.DataParallel(model)
checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device)
model.load_state_dict(checkpoint['model'])
img = torch.rand(1,3,480,640).to(torch.float32)
pdepth = model.forward(img)
print(pdepth)
</code>
And the error message gives:
<code>
Traceback (most recent call last):
  File "/data2/zq/VA-DepthNet/test_img.py", line 25, in <module>
    pdepth = model.forward(img)
  File "/home/zq/micromamba/envs/zoe/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zq/micromamba/envs/zoe/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/zq/VA-DepthNet/vadepthnet/networks/vadepthnet.py", line 302, in forward
    d = self.vlayer(x)
  File "/home/zq/micromamba/envs/zoe/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data2/zq/VA-DepthNet/vadepthnet/networks/vadepthnet.py", line 187, in forward
    x, _ = torch.linalg.solve(ATB, ATA+jitter)
RuntimeError: linalg.solve: A must be batches of square matrices, but they are 1200 by 1 matrices
</code>
Could you add a user case on random image inference please? Thanks in advance!

**Comment by cnexah** [comment]
Hi, thank you for you issue.
I think the problem is the version of PyTorch.
In line: 
https://github.com/cnexah/VA-DepthNet/blob/44061e1f5833eb59835b429850ff759b6bc23648/vadepthnet/networks/vadepthnet.py#L186C16-L186C21

If your version <= 1.7.1, please use x, _ = torch.solve(ATB, ATA+jitter)
If your version >= 1.8.0, please use x = torch.linalg.solve(ATA+jitter, ATB)

**Comment by fatginger1024** [comment]
Thanks, it fixed my problem!

**Comment by dasda-asd** [comment]
> Hi there! I was trying to get your wondnerful model tested on a random image when I encountered this bug, could you please help me out there? Below is the code to reproduce the error: ` import torch from vadepthnet.networks.vadepthnet import VADepthNet device = torch.device("cuda" if torch.cuda.is_available() else "cpu") print("device: %s" % device) model = VADepthNet(max_depth=2, prior_mean=.6, img_size=(480, 640)) model = torch.nn.DataParallel(model) checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device) model.load_state_dict(checkpoint['model']) img = torch.rand(1,3,480,640).to(torch.float32) pdepth = model.forward(img) print(pdepth) ` And the error message gives: ` Traceback (most recent call last): File "/data2/zq/VA-DepthNet/test_img.py", line 25, in pdepth = model.forward(img) File "/home/zq/micromamba/envs/zoe/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/zq/micromamba/envs/zoe/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/data2/zq/VA-DepthNet/vadepthnet/networks/vadepthnet.py", line 302, in forward d = self.vlayer(x) File "/home/zq/micromamba/envs/zoe/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl return forward_call(*input, **kwargs) File "/data2/zq/VA-DepthNet/vadepthnet/networks/vadepthnet.py", line 187, in forward x, _ = torch.linalg.solve(ATB, ATA+jitter) RuntimeError: linalg.solve: A must be batches of square matrices, but they are 1200 by 1 matrices ` Could you add a user case on random image inference please? Thanks in advance!

After I run your example, the following error occurs.

 Traceback (most recent call last):
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\test.py", line 12, in <module>
    pdepth = model.forward(img)
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\parallel\data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\vadepthnet\networks\vadepthnet.py", line 306, in forward
    var_loss = self.var_loss(x, d, gts)
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\vadepthnet\networks\loss.py", line 38, in forward
    loss = loss + self.single(x, d, gts)
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\vadepthnet\networks\loss.py", line 45, in single
    gt = gts.clone()
AttributeError: 'NoneType' object has no attribute 'clone'

How can I solve this problem? Thank you!

**Comment by cnexah** [comment]
Hi, please add 'model.eval()' before  'pdepth = model.forward(img)'

**Comment by dasda-asd** [comment]
> Hi, please add 'model.eval()' before 'pdepth = model.forward(img)'

Thanks you, it fixed my problem!

I saw on kitti's website that the code processes an image in 0.1 seconds, and the environment is configured at 1 core@2.5 Ghz (Python). My environment is configured with pytorch-gpu v1.13.0, cuda 11.7, python v3.9.7, and it takes about 0.2 seconds to process an image.
How can I reduce the time it takes to process an image? It's important to me.
Can you describe the details of the environment configuration to 1 core @ 2.5 Ghz (Python)?

**Comment by cnexah** [comment]
Hi, sorry for the confusion. In fact, I also use GPU. 
I think the running time depends on your GPU type.
Otherwise I would suggest to try smaller network or use mixed precision at evaluation.

**Comment by dasda-asd** [comment]
> Hi, sorry for the confusion. In fact, I also use GPU. I think the running time depends on your GPU type. Otherwise I would suggest to try smaller network or use mixed precision at evaluation.

Thank you for your answer.
Can you give us an example code to test a image(480 x  640  pixels)? I am a beginner and I am very interested in your thesis work.

**Comment by cnexah** [comment]
Thank you for your interest!

import torch
from PIL import Image
import numpy as np
from vadepthnet.networks.vadepthnet import VADepthNet

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device: %s" % device)

model = VADepthNet(max_depth=10,
prior_mean=1.54,
img_size=(480, 640))
model = torch.nn.DataParallel(model)
checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device)
model.load_state_dict(checkpoint['model'])
model.eval()
img = Image.open(image_path)
img = np.asarray(img, dtype=np.float32) / 255.0
img = torch.from_numpy(img).cuda().unsqueeze(0)
pdepth = model.forward(img)
print(pdepth)

**Comment by kangjiahe** [comment]
> Thank you for your interest!
> 
> import torch from PIL import Image import numpy as np from vadepthnet.networks.vadepthnet import VADepthNet
> 
> device = torch.device("cuda" if torch.cuda.is_available() else "cpu") print("device: %s" % device)
> 
> model = VADepthNet(max_depth=10, prior_mean=1.54, img_size=(480, 640)) model = torch.nn.DataParallel(model) checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device) model.load_state_dict(checkpoint['model']) model.eval() img = Image.open(image_path) img = np.asarray(img, dtype=np.float32) / 255.0 img = torch.from_numpy(img).cuda().unsqueeze(0) pdepth = model.forward(img) print(pdepth)

Thank you for your answer.
I tested the image resolution at 640 x 480. The width is 640 pixels and the height is 480 pixels.
Could you please help me out there?

And the error message gives:
device: cuda
D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\test-author.py", line 19, in <module>
    pdepth = model.forward(img)
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\parallel\data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\vadepthnet\networks\vadepthnet.py", line 295, in forward
    x2, x3, x4, x5 = self.backbone(x)
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\vadepthnet\networks\swin_transformer.py", line 592, in forward
    x = self.patch_embed(x)
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\vadepthnet\networks\swin_transformer.py", line 429, in forward
    x = self.proj(x)  # B C Wh Ww
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [192, 3, 4, 4], expected input[1, 480, 640, 4] to have 3 channels, but got 480 channels instead

**Comment by cnexah** [comment]
Sorry for the mistake.
Please try the following code again:

import torch
from PIL import Image
import numpy as np
from vadepthnet.networks.vadepthnet import VADepthNet

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device: %s" % device)

model = VADepthNet(max_depth=10,
prior_mean=1.54,
img_size=(480, 640))
model = torch.nn.DataParallel(model)
checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device)
model.load_state_dict(checkpoint['model'])
model.eval()
img = Image.open(image_path)
img = np.asarray(img, dtype=np.float32) / 255.0
img = torch.from_numpy(img).cuda().permute(2,0,1).unsqueeze(0)
pdepth = model.forward(img)
print(pdepth)

**Comment by kangjiahe** [comment]
> Sorry for the mistake. Please try the following code again:
> 
> import torch from PIL import Image import numpy as np from vadepthnet.networks.vadepthnet import VADepthNet
> 
> device = torch.device("cuda" if torch.cuda.is_available() else "cpu") print("device: %s" % device)
> 
> model = VADepthNet(max_depth=10, prior_mean=1.54, img_size=(480, 640)) model = torch.nn.DataParallel(model) checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device) model.load_state_dict(checkpoint['model']) model.eval() img = Image.open(image_path) img = np.asarray(img, dtype=np.float32) / 255.0 img = torch.from_numpy(img).cuda().permute(2,0,1).unsqueeze(0) pdepth = model.forward(img) print(pdepth)

Thanks you, it fixed my problem!
But I have encountered a new problem.

I ran the code and the result is as follows.

code:
import torch
from PIL import Image
import numpy as np
from vadepthnet.networks.vadepthnet import VADepthNet

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device: %s" % device)

model = VADepthNet(max_depth=10,
prior_mean=1.54,
img_size=(480, 640))
model = torch.nn.DataParallel(model)
checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device)
model.load_state_dict(checkpoint['model'])
model.eval()
img = Image.open("./dataset/nyu_depth_v2/official_splits/test/bathroom/rgb_00045.jpg")
img = np.asarray(img, dtype=np.float32) / 255.0
print(image.shape)
img = torch.from_numpy(img).cuda().permute(2,0,1).unsqueeze(0)
print(img)
pdepth = model.forward(img)
print(pdepth)

result:
(480, 640, 3)
tensor([[[[0.0039, 0.0000, 0.0000,  ..., 0.0039, 0.0000, 0.0000],
          [0.0000, 0.0078, 0.0000,  ..., 0.0039, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0039, 0.0039, 0.0000,  ..., 0.0000, 0.0000, 0.0039],
          [0.0039, 0.0039, 0.0000,  ..., 0.0000, 0.0039, 0.0039],
          [0.0039, 0.0078, 0.0039,  ..., 0.0000, 0.0039, 0.0039]],

         [[0.0078, 0.0000, 0.0078,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0118, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
          [0.0039, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0039],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0039,  ..., 0.0000, 0.0000, 0.0000]],

         [[0.0157, 0.0078, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
          [0.0078, 0.0196, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0118, 0.0078, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          ...,
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000]]]],
       device='cuda:0')
tensor([[[[1.9212, 1.8042, 1.7987,  ..., 1.7313, 1.7186, 1.6955],
          [1.8684, 1.6552, 1.6369,  ..., 1.7597, 1.7681, 1.7380],
          [1.8638, 1.6497, 1.6298,  ..., 1.7546, 1.7601, 1.7015],
          ...,
          [1.4484, 1.3492, 1.2887,  ..., 1.6790, 1.6549, 1.7012],
          [1.4551, 1.3505, 1.2909,  ..., 1.6726, 1.6487, 1.6947],
          [1.4531, 1.2995, 1.2371,  ..., 1.6784, 1.6737, 1.6048]]]],
       device='cuda:0', grad_fn=<MulBackward0>)


At the point,  I modify the nyudepthv2_test_files_with_gt.txt file. The nyudepthv2_test_files_with_gt.txt file contains only 
"bathroom/rgb_00045.jpg bathroom/sync_depth_00045.png 518.8579"
After that, I run commands like this.  "python ./vadepthnet/eval.py ./configs/arguments_eval_nyu.txt".

result:
D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
== Total number of parameters: 261660777
== Total number of learning parameters: 261660777
== Model Initialized
== Loading checkpoint './vadepthnet_nyu.pth'
== Loaded checkpoint './vadepthnet_nyu.pth'
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
print("torch.autograd.Variable(eval_sample_batched['image'].cuda())")
tensor([[[[-2.1008, -2.1179, -2.1179,  ..., -2.1008, -2.1179, -2.1179],
          [-2.1179, -2.0837, -2.1179,  ..., -2.1008, -2.1179, -2.1179],
          [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
          ...,
          [-2.1008, -2.1008, -2.1179,  ..., -2.1179, -2.1179, -2.1008],
          [-2.1008, -2.1008, -2.1179,  ..., -2.1179, -2.1008, -2.1008],
          [-2.1008, -2.0837, -2.1008,  ..., -2.1179, -2.1008, -2.1008]],

         [[-2.0007, -2.0357, -2.0007,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -1.9832, -2.0182,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0182, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0182],
          ...,
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
          [-2.0357, -2.0357, -2.0182,  ..., -2.0357, -2.0357, -2.0357]],

         [[-1.7347, -1.7696, -1.7870,  ..., -1.8044, -1.8044, -1.8044],
          [-1.7696, -1.7173, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.7522, -1.7696, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          ...,
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
          [-1.8044, -1.7870, -1.7870,  ..., -1.8044, -1.8044, -1.8044]]]],
       device='cuda:0')
print(model(image))
tensor([[[[1.9691, 1.8909, 1.8851,  ..., 1.8715, 1.8699, 1.7947],
          [1.9140, 1.7571, 1.7391,  ..., 1.8017, 1.8093, 1.7648],
          [1.9024, 1.7536, 1.7337,  ..., 1.7848, 1.7932, 1.7503],
          ...,
          [1.5392, 1.5082, 1.4695,  ..., 1.6318, 1.6443, 1.7523],
          [1.5329, 1.4997, 1.4632,  ..., 1.6349, 1.6457, 1.7431],
          [1.4974, 1.3821, 1.3284,  ..., 1.6207, 1.6330, 1.6384]]]],
       device='cuda:0')
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.33s/it]
Computing errors for 1 eval samples , post_process:  False
  silog, abs_rel,   log10,     rms,  sq_rel, log_rms,      d1,      d2,      d3
 9.7690,  0.1568,  0.0610,  0.2132,  0.0427,  0.1710,  0.9286,  0.9526,  0.9998

The same photo input, running two different codes, results in different photo preprocessing results and depth estimation results. 
What is the reason for this? How can I solve this problem? Thank you!

**Comment by cnexah** [comment]
Thank you for your check!
Sorry for the mistake again!

Please try the following code:
import torch
from PIL import Image
import numpy as np
from vadepthnet.networks.vadepthnet import VADepthNet
from vadepthnet.dataloaders.dataloader import ToTensor

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device: %s" % device)

model = VADepthNet(max_depth=10,
prior_mean=1.54,
img_size=(480, 640))
model = torch.nn.DataParallel(model)
checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device)
model.load_state_dict(checkpoint['model'])
model.eval()
img = Image.open(image_path)
img = np.asarray(img, dtype=np.float32) / 255.0
#img = torch.from_numpy(img).cuda().unsqueeze(0)
img = ToTensor.to_tensor(img)
img = ToTensor.normalize(img)
img = img.unsqueeze(0)
pdepth = model.forward(img)
print(pdepth)

**Comment by kangjiahe** [comment]
> Thank you for your check! Sorry for the mistake again!
> 
> Please try the following code: import torch from PIL import Image import numpy as np from vadepthnet.networks.vadepthnet import VADepthNet from vadepthnet.dataloaders.dataloader import ToTensor
> 
> device = torch.device("cuda" if torch.cuda.is_available() else "cpu") print("device: %s" % device)
> 
> model = VADepthNet(max_depth=10, prior_mean=1.54, img_size=(480, 640)) model = torch.nn.DataParallel(model) checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device) model.load_state_dict(checkpoint['model']) model.eval() img = Image.open(image_path) img = np.asarray(img, dtype=np.float32) / 255.0 #img = torch.from_numpy(img).cuda().unsqueeze(0) img = ToTensor.to_tensor(img) img = ToTensor.normalize(img) img = img.unsqueeze(0) pdepth = model.forward(img) print(pdepth)

Irun the above code.
I have encountered a new problem.
And the error message gives:
D:\xiaohe\anaconda\envs\zoedepth\python.exe D:\xiaohe\VA-depthnet\VA-DepthNet-main\test-author.py 
Traceback (most recent call last):
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\test-author.py", line 5, in <module>
    from vadepthnet.dataloaders.dataloader import ToTensor
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\vadepthnet\dataloaders\dataloader.py", line 11, in <module>
    from utils import DistributedSamplerNoEvenlyDivisible
ModuleNotFoundError: No module named 'utils'

**Comment by kangjiahe** [comment]
> Thank you for your check! Sorry for the mistake again!
> 
> Please try the following code: import torch from PIL import Image import numpy as np from vadepthnet.networks.vadepthnet import VADepthNet from vadepthnet.dataloaders.dataloader import ToTensor
> 
> device = torch.device("cuda" if torch.cuda.is_available() else "cpu") print("device: %s" % device)
> 
> model = VADepthNet(max_depth=10, prior_mean=1.54, img_size=(480, 640)) model = torch.nn.DataParallel(model) checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device) model.load_state_dict(checkpoint['model']) model.eval() img = Image.open(image_path) img = np.asarray(img, dtype=np.float32) / 255.0 #img = torch.from_numpy(img).cuda().unsqueeze(0) img = ToTensor.to_tensor(img) img = ToTensor.normalize(img) img = img.unsqueeze(0) pdepth = model.forward(img) print(pdepth)

I run the above code.
I have encountered a new problem.
And the error message gives:
D:\xiaohe\anaconda\envs\zoedepth\python.exe D:\xiaohe\VA-depthnet\VA-DepthNet-main\test-author.py 
device: cuda
D:\xiaohe\anaconda\envs\zoedepth\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "D:\xiaohe\VA-depthnet\VA-DepthNet-main\test-author.py", line 20, in <module>
    img = ToTensor.to_tensor(img)
TypeError: to_tensor() missing 1 required positional argument: 'pic'

**Comment by cnexah** [comment]
Thank you for your check!
Sorry for the mistake again!

Please try the following code:
import torch
from PIL import Image
import numpy as np
from vadepthnet.networks.vadepthnet import VADepthNet
from vadepthnet.dataloaders.dataloader import ToTensor

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device: %s" % device)

model = VADepthNet(max_depth=10,
prior_mean=1.54,
img_size=(480, 640))
model = torch.nn.DataParallel(model)
checkpoint = torch.load('vadepthnet_nyu.pth', map_location=device)
model.load_state_dict(checkpoint['model'])
model.eval()
img = Image.open(image_path)
img = np.asarray(img, dtype=np.float32) / 255.0
#img = torch.from_numpy(img).cuda().unsqueeze(0)

totensor = ToTensor('test')
img = totensor.to_tensor(img)
img = totensor.normalize(img)
img = img.unsqueeze(0)
pdepth = model.forward(img)
print(pdepth)
